### ISSUE TITLE
谢谢你！

### ISSUE THREAD

**Issue by ecogit** [pillepalle1/zhongwen-study#1]
Vielen Dank für's teilen dieser Kursunterlagen. Ein guter Grund mehr das Thema endlich regelmässig anzupacken. Dir unterdessen viel Erfolg beim meistern dieser Sprache und viel Spass in Macau. 家走！ Gruss aus Chengdu 🍻

**Comment by pillepalle1** [comment]
Kein Problem und viel Erfolg beim Selbststudium
